shortcut_module_link: 0
settings:
  layouts_enable: 1
  template_suggestion_page: sparta
  master_layout: minima
  selected_layout_minima: sparta
  max_width_enable: 0
  max_width_value: ''
  max_width_unit: ''
  layouts_no_mq_sparta: 1
  enable_backups: 1
  enable_extensions: 1
  enable_fonts: 1
  enable_titles: 1
  enable_images: 1
  enable_touch_icons: 1
  enable_libraries: 1
  enable_custom_css: 1
  enable_markup_overrides: 1
  show_page_suggestions: 0
  show_window_size: 0
  livereload: 0
  livereload_snippet: ''
  devel_layout: 0
  nuke_toolbar: 0
  default_layout_provider: at_minimal
  template_suggestion_provider_page: at_minimal
  template_suggestion_plugin_page: minima
  base_font_type: ''
  base_font: bf-a
  base_font_gwf: ''
  base_font_gwf_add_styles: 0
  base_font_gwf_add_styles_300: 0
  base_font_gwf_add_styles_300italic: 0
  base_font_gwf_add_styles_400: 0
  base_font_gwf_add_styles_400italic: 0
  base_font_gwf_add_styles_700: 0
  base_font_gwf_add_styles_700italic: 0
  base_font_gwf_add_charsets: 0
  base_font_gwf_add_charsets_latin: 0
  base_font_gwf_add_charsets_latin-ext: 0
  base_font_gwf_add_charsets_greek: 0
  base_font_gwf_add_charsets_greek-ext: 0
  base_font_gwf_add_charsets_cyrillic: 0
  base_font_gwf_add_charsets_cyrillic-ext: 0
  base_font_gwf_add_charsets_khmer: 0
  base_font_gwf_add_charsets_vietnamese: 0
  base_font_cfs: ''
  base_font_size: '16'
  site_name_font_type: '<none>'
  site_name_font: bf-sss
  site_name_font_gwf: ''
  site_name_font_gwf_add_styles: 0
  site_name_font_gwf_add_styles_300: 0
  site_name_font_gwf_add_styles_300italic: 0
  site_name_font_gwf_add_styles_400: 0
  site_name_font_gwf_add_styles_400italic: 0
  site_name_font_gwf_add_styles_700: 0
  site_name_font_gwf_add_styles_700italic: 0
  site_name_font_gwf_add_charsets: 0
  site_name_font_gwf_add_charsets_latin: 0
  site_name_font_gwf_add_charsets_latin-ext: 0
  site_name_font_gwf_add_charsets_greek: 0
  site_name_font_gwf_add_charsets_greek-ext: 0
  site_name_font_gwf_add_charsets_cyrillic: 0
  site_name_font_gwf_add_charsets_cyrillic-ext: 0
  site_name_font_gwf_add_charsets_khmer: 0
  site_name_font_gwf_add_charsets_vietnamese: 0
  site_name_font_size: ''
  site_slogan_font_type: '<none>'
  site_slogan_font: bf-sss
  site_slogan_font_gwf: ''
  site_slogan_font_gwf_add_styles: 0
  site_slogan_font_gwf_add_styles_300: 0
  site_slogan_font_gwf_add_styles_300italic: 0
  site_slogan_font_gwf_add_styles_400: 0
  site_slogan_font_gwf_add_styles_400italic: 0
  site_slogan_font_gwf_add_styles_700: 0
  site_slogan_font_gwf_add_styles_700italic: 0
  site_slogan_font_gwf_add_charsets: 0
  site_slogan_font_gwf_add_charsets_latin: 0
  site_slogan_font_gwf_add_charsets_latin-ext: 0
  site_slogan_font_gwf_add_charsets_greek: 0
  site_slogan_font_gwf_add_charsets_greek-ext: 0
  site_slogan_font_gwf_add_charsets_cyrillic: 0
  site_slogan_font_gwf_add_charsets_cyrillic-ext: 0
  site_slogan_font_gwf_add_charsets_khmer: 0
  site_slogan_font_gwf_add_charsets_vietnamese: 0
  site_slogan_font_size: ''
  page_title_font_type: '<none>'
  page_title_font: bf-sss
  page_title_font_gwf: ''
  page_title_font_gwf_add_styles: 0
  page_title_font_gwf_add_styles_300: 0
  page_title_font_gwf_add_styles_300italic: 0
  page_title_font_gwf_add_styles_400: 0
  page_title_font_gwf_add_styles_400italic: 0
  page_title_font_gwf_add_styles_700: 0
  page_title_font_gwf_add_styles_700italic: 0
  page_title_font_gwf_add_charsets: 0
  page_title_font_gwf_add_charsets_latin: 0
  page_title_font_gwf_add_charsets_latin-ext: 0
  page_title_font_gwf_add_charsets_greek: 0
  page_title_font_gwf_add_charsets_greek-ext: 0
  page_title_font_gwf_add_charsets_cyrillic: 0
  page_title_font_gwf_add_charsets_cyrillic-ext: 0
  page_title_font_gwf_add_charsets_khmer: 0
  page_title_font_gwf_add_charsets_vietnamese: 0
  page_title_font_size: ''
  node_title_font_type: '<none>'
  node_title_font: bf-sss
  node_title_font_gwf: ''
  node_title_font_gwf_add_styles: 0
  node_title_font_gwf_add_styles_300: 0
  node_title_font_gwf_add_styles_300italic: 0
  node_title_font_gwf_add_styles_400: 0
  node_title_font_gwf_add_styles_400italic: 0
  node_title_font_gwf_add_styles_700: 0
  node_title_font_gwf_add_styles_700italic: 0
  node_title_font_gwf_add_charsets: 0
  node_title_font_gwf_add_charsets_latin: 0
  node_title_font_gwf_add_charsets_latin-ext: 0
  node_title_font_gwf_add_charsets_greek: 0
  node_title_font_gwf_add_charsets_greek-ext: 0
  node_title_font_gwf_add_charsets_cyrillic: 0
  node_title_font_gwf_add_charsets_cyrillic-ext: 0
  node_title_font_gwf_add_charsets_khmer: 0
  node_title_font_gwf_add_charsets_vietnamese: 0
  node_title_font_size: ''
  comment_title_font_type: '<none>'
  comment_title_font: bf-sss
  comment_title_font_gwf: ''
  comment_title_font_gwf_add_styles: 0
  comment_title_font_gwf_add_styles_300: 0
  comment_title_font_gwf_add_styles_300italic: 0
  comment_title_font_gwf_add_styles_400: 0
  comment_title_font_gwf_add_styles_400italic: 0
  comment_title_font_gwf_add_styles_700: 0
  comment_title_font_gwf_add_styles_700italic: 0
  comment_title_font_gwf_add_charsets: 0
  comment_title_font_gwf_add_charsets_latin: 0
  comment_title_font_gwf_add_charsets_latin-ext: 0
  comment_title_font_gwf_add_charsets_greek: 0
  comment_title_font_gwf_add_charsets_greek-ext: 0
  comment_title_font_gwf_add_charsets_cyrillic: 0
  comment_title_font_gwf_add_charsets_cyrillic-ext: 0
  comment_title_font_gwf_add_charsets_khmer: 0
  comment_title_font_gwf_add_charsets_vietnamese: 0
  comment_title_font_size: ''
  block_title_font_type: '<none>'
  block_title_font: bf-sss
  block_title_font_gwf: ''
  block_title_font_gwf_add_styles: 0
  block_title_font_gwf_add_styles_300: 0
  block_title_font_gwf_add_styles_300italic: 0
  block_title_font_gwf_add_styles_400: 0
  block_title_font_gwf_add_styles_400italic: 0
  block_title_font_gwf_add_styles_700: 0
  block_title_font_gwf_add_styles_700italic: 0
  block_title_font_gwf_add_charsets: 0
  block_title_font_gwf_add_charsets_latin: 0
  block_title_font_gwf_add_charsets_latin-ext: 0
  block_title_font_gwf_add_charsets_greek: 0
  block_title_font_gwf_add_charsets_greek-ext: 0
  block_title_font_gwf_add_charsets_cyrillic: 0
  block_title_font_gwf_add_charsets_cyrillic-ext: 0
  block_title_font_gwf_add_charsets_khmer: 0
  block_title_font_gwf_add_charsets_vietnamese: 0
  block_title_font_size: ''
  selectors_font_type: '<none>'
  selectors_font: bf-sss
  selectors_font_gwf: ''
  selectors_font_add_styles: 0
  selectors_font_add_styles_300: 0
  selectors_font_add_styles_300italic: 0
  selectors_font_add_styles_400: 0
  selectors_font_add_styles_400italic: 0
  selectors_font_add_styles_700: 0
  selectors_font_add_styles_700italic: 0
  selectors_font_add_charsets: 0
  selectors_font_add_charsets_latin: 0
  selectors_font_add_charsets_latin-ext: 0
  selectors_font_add_charsets_greek: 0
  selectors_font_add_charsets_greek-ext: 0
  selectors_font_add_charsets_cyrillic: 0
  selectors_font_add_charsets_cyrillic-ext: 0
  selectors_font_add_charsets_khmer: 0
  selectors_font_add_charsets_vietnamese: 0
  selectors_font_cfs: ''
  selectors_css: ''
  site_name_case: none
  site_name_weight: '700'
  site_name_alignment: left
  site_slogan_case: none
  site_slogan_weight: '400'
  site_slogan_alignment: left
  page_title_case: none
  page_title_weight: '700'
  page_title_alignment: left
  node_title_case: none
  node_title_weight: '700'
  node_title_alignment: left
  comment_title_case: none
  comment_title_weight: '700'
  comment_title_alignment: left
  block_title_case: none
  block_title_weight: '700'
  block_title_alignment: left
  image_alignment_article_node_full: none
  image_alignment_article_node_teaser: none
  image_captions_article_node_full: 0
  image_captions_article_node_teaser: 0
  image_count_article_node_full: 0
  image_count_article_node_teaser: 0
  image_alignment_page_node_full: none
  image_alignment_page_node_teaser: none
  image_captions_page_node_full: 0
  image_captions_page_node_teaser: 0
  image_count_page_node_full: 0
  image_count_page_node_teaser: 0
  icon_path_default: images/default-60x60.png
  apple_touch_icon_path_ipad: images/iphone-retina-120x120.png
  apple_touch_icon_path_iphone_retina: images/ipad-standard-76x76.png
  apple_touch_icon_path_ipad_retina: images/ipad-retina-152x152.png
  apple_touch_icon_precomposed: 0
  libraries_enable: 0
  drupal_core_drupal_debounce: 0
  drupal_core_domready: 0
  drupal_core_jquery: 0
  drupal_core_jquery_once: 0
  drupal_core_jquery_form: 0
  drupal_core_jquery_bbq: 0
  drupal_core_matchmedia: 0
  drupal_core_jquery_ui_core: 0
  drupal_core_jquery_ui_accordion: 0
  drupal_core_jquery_ui_autocomplete: 0
  drupal_core_jquery_ui_button: 0
  drupal_core_jquery_ui_datepicker: 0
  drupal_core_jquery_ui_dialog: 0
  drupal_core_jquery_ui_draggable: 0
  drupal_core_jquery_ui_droppable: 0
  drupal_core_jquery_ui_menu: 0
  drupal_core_jquery_ui_mouse: 0
  drupal_core_jquery_ui_position: 0
  drupal_core_jquery_ui_progressbar: 0
  drupal_core_jquery_ui_resizable: 0
  drupal_core_jquery_ui_selectable: 0
  drupal_core_jquery_ui_slider: 0
  drupal_core_jquery_ui_sortable: 0
  drupal_core_jquery_ui_spinner: 0
  drupal_core_jquery_ui_tabs: 0
  drupal_core_jquery_ui_tooltip: 0
  drupal_core_jquery_ui_widget: 0
  drupal_core_jquery_effects_core: 0
  drupal_core_jquery_effects_blind: 0
  drupal_core_jquery_effects_bounce: 0
  drupal_core_jquery_effects_clip: 0
  drupal_core_jquery_effects_drop: 0
  drupal_core_jquery_effects_explode: 0
  drupal_core_jquery_effects_fade: 0
  drupal_core_jquery_effects_fold: 0
  drupal_core_jquery_effects_highlight: 0
  drupal_core_jquery_effects_pulsate: 0
  drupal_core_jquery_effects_scale: 0
  drupal_core_jquery_effects_shake: 0
  drupal_core_jquery_effects_slide: 0
  drupal_core_jquery_effects_transfer: 0
  drupal_core_jquery_ui_touch-punch: 0
  drupal_core_underscore: 0
  drupal_core_backbone: 0
  custom_css: '/* Custom CSS */'
  breadcrumb_label: 0
  breadcrumb_home: 0
  breadcrumb_title: 0
  breadcrumb_separator: ''
  login_block_placeholder_labels: 0
  horizontal_login_block: 0
  login_block_remove_links: 0
  comments_hide_title: 0
  unset_menu_titles: 0
  skip_link_target: ''
  attribution_toggle: 0
features:
  logo: 1
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 1
  path: ''
