<?php

/**
 * Implements hook_theme().
 */
function webprofiler_theme() {
  return array(
    'webprofiler_loader' => array(
      'template' => 'Profiler/webprofiler_loader',
      'variables' => array('token' => NULL, 'profiler_url' => NULL),
    ),
    'webprofiler_toolbar' => array(
      'template' => 'Profiler/webprofiler_toolbar',
      'variables' => array('token' => NULL, 'templates' => array(), 'profile' => NULL, 'profiler_url' => NULL),
    ),
    'webprofiler_panel' => array(
      'template' => 'Profiler/webprofiler_panel',
      'variables' => array(
        'template' => array(),
        'profile' => NULL,
        'name' => NULL,
        'summary' => NULL,
        'content' => NULL,
      ),
    ),
    'webprofiler_resume' => array(
      'template' => 'Profiler/webprofiler_resume',
      'variables' => array(
        'template' => array(),
        'profile' => NULL,
        'name' => NULL
      ),
    ),
    'webprofiler_db_panel' => array(
      'template' => 'Profiler/webprofiler_db_panel',
      'variables' => array(
        'query' => NULL,
        'table' => NULL,
        'explain' => FALSE,
        'query_type' => NULL,
        'position' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function webprofiler_permission() {
  $perms = array(
    'access webprofiler' => array(
      'title' => t('Access webprofiler'),
      'description' => t('Access webprofiler collected data.'),
      'restrict access' => TRUE,
    ),
    'view webprofiler toolbar' => array(
      'title' => t('View webprofiler toolbar'),
      'description' => t('View webprofiler toolbar.'),
    ),
  );

  return $perms;
}

/**
 * Implements hook_file_download().
 */
function webprofiler_file_download($uri) {
  $scheme = file_uri_scheme($uri);
  $target = file_uri_target($uri);
  if ($scheme == 'temporary' && $target == 'profiles.tar.gz') {
    return array(
      'Content-disposition' => 'attachment; filename="profiles.tar.gz"',
    );
  }
}

/**
 * Implements hook_cache_flush().
 */
function webprofiler_cache_flush() {
  $config = \Drupal::configFactory()->get('webprofiler.config');

  if ($config->get('purge_on_cache_clear')) {
    $profiler = \Drupal::service('profiler');
    $profiler->purge();
  }
}
