id: theme.at_core.mobile
uuid: 676e11ac-c254-415a-881c-28786167edjb
name: mobile
label: Mobile
mediaQuery: '(min-width: 0em)'
source: at_core
sourceType: theme
weight: 1
multipliers:
  1x: 1x
status: true
langcode: en
