id: theme.at_core.narrow
uuid: da7ce8eb-f006-4a2f-8557-87ac4f62d5jb
name: narrow
label: Narrow
mediaQuery: 'all and (min-width: 35em) and (max-width: 60em)'
source: at_core
sourceType: theme
weight: 1
multipliers:
  1x: 1x
status: true
langcode: en
