<?php

/**
 * @file
 * Functions to support theming in the mariquecalcus theme.
 */

use Drupal\Component\Utility\String;
use Drupal\Component\Utility\Xss;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function mariquecalcus_preprocess_html(&$variables) {
  //debug($variables);
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function mariquecalcus_preprocess_page(&$variables) {
  //dpm($variables);
}
